at least that what I could do, sorry for everything
team-dut/i-ran-out-of-name-help pull request #6
Opened 2023-12-19 16:02 UTC by HuySimpLo

Adding the character file 
- One boss (with chasing algorithm)
- 1 player
- 1 aggressive, 1 defensive, 1 normal movement NPCs
- And bunch of changes that I couldn't've figured how to fix. (gomenasai)

2023-12-20 08:18 UTC, Swyreee requested changes
Có gì mấy cái trong `src/Engine/` với `.idea` mày revert lại đi.

Cảm ơn vì đã cố gắng <3

2023-12-21 08:12 UTC, Swyreee requested changes

2023-12-21 08:12 UTC, Swyreee commented on src/Game/Entity/PlayerSquare.java
Xóa file này đi. Mình có `GameScreen.java` rồi.

2023-12-21 08:12 UTC, Swyreee commented on src/Game/Entity/NPC.java
> +}
Nên tách ra class riêng.

2023-12-21 08:12 UTC, Swyreee commented on src/Game/Entity/NPC.java
> +}
Nên tách ra class riêng.

2023-12-21 08:12 UTC, Swyreee commented on src/Game/Entity/NPC.java
> +}
Nên tách ra class riêng.

2023-12-21 08:14 UTC, Swyreee commented
Sau khi đọc qua một chút thì có vẻ `<Player>.update()` là để cập nhật lại `x` và `y` mới.

2023-12-21 10:43 UTC, DoTanLoc2003 commented on src/Game/Entity/Player.java
> +
thêm boolean aLive = true; trường hợp bị boss chạm tới (isCollideWith) thì không vẽ nhân vật đó nữa

2023-12-21 10:52 UTC, Swyreee submitted a review, later dismissed
Có vẻ ổn

2023-12-21 10:54 UTC, Swyreee approved these changes
10/10, vẫn còn nhiều thứ nên làm như là keybind, thuật toán để quái đuổi theo player, nhưng thế này là được rôi.

2023-12-22 04:27 UTC, DoTanLoc2003 requested changes
thêm biến alive kiểm tra player/NPC còn sống hay không

2023-12-22 04:27 UTC, DoTanLoc2003 commented on src/Game/Entity/Player.java
> +
```suggestion
private boolean alive = true;
```

2023-12-22 04:28 UTC, Swyreee requested changes

2023-12-22 04:28 UTC, Swyreee commented on src/Game/Entity/Player.java
> +private boolean alive = true;
```suggestion
    private boolean alive = true;
```

2023-12-22 04:29 UTC, Swyreee approved these changes

2023-12-22 04:29 UTC, DoTanLoc2003 approved these changes

2023-12-22 04:30 UTC, merged