Maze
team-dut/i-ran-out-of-name-help pull request #7
Opened 2023-12-22 12:17 UTC by MaiXuanThien

2023-12-22 12:23 UTC, DoTanLoc2003 reviewed
Chưa ổn lắm, cần điều chỉnh thêm

2023-12-22 12:23 UTC, DoTanLoc2003 commented on src/Game/Maze/Image.java
> +        final BufferedImage edgeright = ImageIO.read(new File("d:\\_maze\resources\\Wall\\wall_edge_right.png"));
để đường dẫn short-cut chứ không phải đường dẫn từ ổ đĩa, chạy trên máy @MaiXuanThien  thì được nhưng máy khác thì không

2023-12-22 12:23 UTC, DoTanLoc2003 commented on src/Game/Maze/Image.java
> +    }
@Swyreee Chỗ này hình như build riêng JFrame cho game = GameScreen rồi. Vô xem lại dùm nhá

2023-12-22 12:23 UTC, DoTanLoc2003 commented on src/Game/Maze/Maze.java
file này test thử chứ không phải file chính, xóa đi. Ngoài ra chưa thấy hàm getMaze() để mang ra ngoài đâu

2023-12-22 12:27 UTC, Swyreee requested changes
Khá nhiều thứ cần phải sửa.

2023-12-22 12:27 UTC, Swyreee commented on src/Game/Maze/Image.java
> +    }
```suggestion
```

`main` ở đây làm gì thế?

2023-12-22 12:27 UTC, Swyreee commented on src/Game/Maze/Maze.java
> +    }
```suggestion
```

ở đây cũng thế luôn

2023-12-22 12:27 UTC, Swyreee commented on src/Game/Maze/Image.java
> +        final BufferedImage edgeright = ImageIO.read(new File("d:\\_maze\resources\\Wall\\wall_edge_right.png"));
Chỗ này không cần hardcode ra làm gì, cứ để là `String` thôi.

```suggestion
        final String edgebottomleft = "Wall/wall_edge_bottom_left.png";
        final String edgebottomright = "Wall/wall_edge_bottom_right.png";
        final String edgetopleft = "Wall/wall_edge_top_left.png";
        final String edgetopright = "Wall/wall_edge_top_right.png";
        final String edgeleft = "Wall/wall_edge_left.png";
        final String edgeright = "Wall/wall_edge_right.png";
```

2023-12-22 12:27 UTC, Swyreee commented on src/Game/Maze/Maze.java
> +            char move = scanner.next().charAt(0);
Mình đang làm game trên GUI, chứ không phải là làm game trên console đâu, đám này ở đây làm gì thế?

2023-12-22 12:54 UTC, MaiXuanThien commented on src/Game/Maze/Maze.java
có hàm getMaze r mà Lộc

2023-12-23 14:12 UTC, Swyreee commented
Reopen

2023-12-24 01:22 UTC, Swyreee requested changes
+ format code lại tí là được

2023-12-24 01:22 UTC, Swyreee commented on src/Game/Maze/Image.java
> +        edgemidright = "wall_edge_mid_right.png";
```suggestion
        edgebottomleft = "Wall/wall_edge_bottom_left.png";
        edgebottomright = "Wall/wall_edge_bottom_right.png";
        edgetopleft = "Wall/wall_edge_top_left.png";
        edgetopright = "Wall/wall_edge_top_right.png";
        edgeleft = "Wall/wall_edge_left.png";
        edgeright = "Wall/wall_edge_right.png";
        edgetshapebottomright = "Wall/wall_edge_tshape_bottom_right";
        edgetshapebottomleft = "Wall/wall_edge_tshape_bottom_left.png";
        edgetshaperight = "Wall/wall_edge_tshape_right.png";
        edgetshapeleft = "Wall/wall_edge_tshape_left.png";
        edgemidleft = "Wall/wall_edge_mid_left.png";
        edgemidright = "Wall/wall_edge_mid_right.png";
```

2023-12-24 01:29 UTC, Swyreee requested changes

2023-12-24 01:29 UTC, Swyreee commented on src/Game/Maze/Maze.java
> +public class Maze extends JFrame  {
chỉnh lại 1 tí:

- cái này dùng thằng file [`GameScreen.java`](https://github.com/team-dut/i-ran-out-of-name-help/blob/main/src/Game/Screen/GameScreen.java) luôn.
```suggestion
public class GameScreen extends Screen {
```

2023-12-24 01:29 UTC, Swyreee commented on src/Game/Maze/Maze.java
> +            super.paint(g);
```suggestion
        public void render(Graphics2D g) {
```

2023-12-24 01:29 UTC, Swyreee commented on src/Game/Maze/Maze.java
> +            });
Chỗ này Lộc nó sẽ code sau, tạm thời xóa đi.

```suggestion
```

2023-12-24 01:29 UTC, Swyreee commented on src/Game/Maze/Maze.java
> +
nếu làm theo cái review phía trên thì cái này không cần thiết đâu.

2023-12-24 01:29 UTC, Swyreee commented on src/Game/Maze/Maze.java
> +            setVisible(true);
chỗ này bỏ luôn
```suggestion
```

2023-12-24 01:29 UTC, Swyreee commented on src/Game/Maze/Image.java
Bưng được gần hết file này qua file `Maze.java`.

2023-12-24 01:29 UTC, Swyreee commented on src/Game/Maze/Maze.java
Sửa theo review và thêm chút format code.

2023-12-24 11:11 UTC, DoTanLoc2003 reviewed
tạm thời ổn

2023-12-25 09:27 UTC, Swyreee approved these changes

2023-12-25 09:31 UTC, merged